type: object
properties:
    success:
        type: boolean
        example: true
    application:
      type: array
      items:
        $ref: "./Application.yaml"
   
    limit:
        type: number
        example: 100
    offset:
        type: number
        example: 0