import express = require("express");
import { userRouter } from "./user";
import { versionRouter } from "./version";
import { qrCodeRouter } from "./qrcode";
import { categoryRouter } from "./category";
import { searchRouter } from "./search";
import { configurationRouter } from "./configuration";
import { emailRouter } from "./email";
import { SMTPConfigRouter } from "./smtp";
import { PostRouter } from "./post";
import { AliasRouter } from "./alias";
import { MenuItemRouter } from "./menuItem";
import { ViewerRouter } from "./viewer";
import { PageRouter } from "./page";
import { WriterRouter } from "./writer";
import { WinnerRouter } from "./winner";
import { TrusteeRouter } from "./trustee";
//import { TemplateRouter } from "./template";
import { filesSetConfigurationRouter } from "./filesSetConfiguration";
import { filesSetRouter } from "./filesSet";
import { fileRouter } from "./file";
import { ApplicationRouter } from "./application";
import { CareerRouter } from "./career";
import { CommentRouter } from "./comment";
import { ServiceRequestRouter } from "./serviceRequest";
import { themeRouter } from "./theme";
import { linkRouter } from "./link";
import { SurveyRouter } from "./survey";
import { SurveyAnswerRouter } from "./surveyAnswer";
import { RequestRouter } from "./request";
//import { permissionRouter } from "./premission";
import { MessageTemplateRouter } from "./messageTemplate";
import { happinessCenterRouter } from "./happinessCenter";
import { subscriberRouter } from "./subscriber";
import { SiteMapRoute } from "./siteMap";
import { TranslateRouter } from "./translate";

import { DetailRouter } from "./detail";
import { ServiceRouter } from "./service";
import { aclRouter } from "./acl";
import { userGroupRouter } from "./userGroup";
import { ReplayRouter } from "./replay";
import { PermissionRouter } from "./permission";
import { BlockRouter } from "./blocks";
import { RateRouter } from "./rate";
import { MigrateionRouter } from "./migration";
import { StatsticRouter } from "./statistics";
import { LastUpdate } from "./lastUpdate";
import { FilterRouter } from "./filter";
import { LogsRouter } from "./logs";
import { NotificationRouter } from "./notification";
import { RedisRouter } from "./redis";
import { ChannelRouter } from "./channel";

const router = express.Router();

router.use("/usergroup", userGroupRouter);
router.use("/acl", aclRouter);
//router.use("/permission", permissionRouter);
router.use("/link", linkRouter);
router.use("/file", fileRouter);
router.use("/file/set", filesSetRouter);
router.use("/file/set/configuration", filesSetConfigurationRouter);
router.use("/category", categoryRouter);
router.use("/post", PostRouter);
router.use("/menuItem", MenuItemRouter);
router.use("/viewer", ViewerRouter);
router.use("/page", PageRouter);
//router.use("/template", TemplateRouter);

router.use("/version", versionRouter);
router.use("/users", userRouter);
router.use("/qrCode", qrCodeRouter);
router.use("/search", searchRouter);
router.use("/configuration", configurationRouter);
router.use("/email", emailRouter);
router.use("/smtp/configuration", SMTPConfigRouter);
router.use("/application", ApplicationRouter);
router.use("/career", CareerRouter);
router.use("/comment", CommentRouter);
router.use("/Service/request", ServiceRequestRouter);
router.use("/theme", themeRouter);
router.use("/survey", SurveyRouter);
router.use("/survey/answer", SurveyAnswerRouter);
router.use("/request", RequestRouter);
router.use("/message/template", MessageTemplateRouter);
router.use("/happiness/center", happinessCenterRouter);
router.use("/subscriber", subscriberRouter);
router.use("/site/map", SiteMapRoute);
router.use("/detail/", DetailRouter);
router.use("/service", ServiceRouter);
router.use("/alias", AliasRouter);
router.use("/replay", ReplayRouter);
router.use("/permission", PermissionRouter);
router.use("/block", BlockRouter);
router.use("/rate", RateRouter);
router.use("/migrate", MigrateionRouter);
router.use("/statistics", StatsticRouter);
router.use("/lastUpdate", LastUpdate);
router.use("/filter", FilterRouter);
router.use("/writer", WriterRouter);
router.use("/winner", WinnerRouter);
router.use("/trustee", TrusteeRouter);
router.use("/channel", ChannelRouter);
router.use("/logs", LogsRouter);
router.use("/notification", NotificationRouter);
router.use("/redis", RedisRouter);
router.use("/translate", TranslateRouter);
export const apiRouter = router;
