export enum CareerDepartment {
    DIRECTOR_GENERAL_OFFICE = "directorGeneralOffice",
    RAK_RECONCILLIATION_AND_COMMERCIAL = "rakReconcilliationAndCommercial",
    CHAIRMAN_OFFICE = "chairmanOffice",
    HUMAN_RESOURCES_DEPARTMENT = "humanResourcesDepartment",
    CORPORATE_COMMUNICATION_OFFICE = "corporateCommunicationOffice",
    INFORMATION_TECHNOLOGY_DEPARTMENT = "informationTechnologyDepartment",
    FINANCIAL_AFFAIRS_DEPARTMENT = "financialAffairsDepartment",
    ADMINISTRATIVE_SERVICE_DEPARTMENT = "administrativeServiceDepartment",
    STRATEGY_AND_FUTURE_DEPARTMENT = "strategyAndFutureDepartment",
    RAK_EXHIBITION_CENTER = "rakExhibitionCenter",
    RAK_SME = "rakSme",
    ECONOMIC_STUDIES_COMMERCIAL_DEPARTMENT = "economicStudiesCommercialDepartment",
    COMMERCIAL_SERVICE_DEPARTMENT = "commercialServiceDepartment",
    INVESTEMENT_PROMOTION_DEPARTMENT = "investementPromotionDepartment",
    CAREER_COORDINATION_DEPARTMENT = "eventCoordinationDepartment",
}
