export enum staticPages {
    NEWS = "/news",
    VIDEOS_GALLERY = "/media/videos-gallery",
    EVENTS = "/media/events",
    LIVE_BROADCASTS = "/media/live-broadcasts",
    PUBLICATIONS = "/media/publications",
    OPEN_DATA = "/open-data/page",
    PHOTOS_GALLERY = "/media/photos-gallery",
    OPEN_DATA_POLICY = "/open-data/open-data-policy",
    POLLS = "/participation/polls",
    OPINION = "/participation/opinion",
    FAQ = "/participation/faq",
    SURVEY = "/participation/survey",
    DIRECTORS = "/aboutus/directors",
    COMITTEES = "/aboutus/committees",
    SPONSORS = "/aboutus/sponsors",
    CUSTOMERS_SATISFACTION = "/aboutus/customers-satisfaction",
    INITIATIVES = "/aboutus/initiatives",
    VACANCES = "/careers/vacances",
    CONTAT_US = "/contactus/contactus",
    RAK_EXHIBITION = "/services/rak-exhibition",
    RAK_SME = "/services/rak-sme",
    STRATEGIC_PLAN = "/aboutus/strategic-plan",
    RAK_ARBITRATION = "/services/rak-arbitration",
}
