export enum PostType {
    ARTICLES = "articles",
    ALL = "all",
    MESSAGES = "messages",
    EVENTS = "events",
    NEWS = "news",
    INITIATIVES = "initiatives",
    INV_OPPS = "investmentOpportunities",
    OPEN_DATAS = "openDatas",
    OPINIONS = "opinions",
    ADS = "advertisments",
    PUBLICATIONS = "publications",
    ALLIANCES = "alliances",
    GENERAL_PAGES = "generalPages",
    LIVE_BROADCASTS = "liveBroadcasts",
    SLIDERS = "sliders",
    FAQ = "faq",
    ROOMS = "rooms",
    NOTIFICATIONS = "notifications",
    INDICATORS = "indicators",
    EVENTS_ON_THIS_DAY = "eventsOnThisDay",
    DIRECTORS = "directors",
    PARTNERS = "partners",
    AWARDS = "awards",
    LAWS = "laws",
    POLICIES = "policies",
    BASIC_PAGE = "basicPage",
    RESEARCHES = "researches",
    ENCYCLOPEDIA = "encyclopedia",
    CHAPTER = "chapter",
    GOALS = "goals",
    //...
}

export enum ViewerType {
    NEWS = "news",
    EVENT = "event",
    ARTICLE = "article",
    BANNER = "banner",
    // ADS,
    // SLIDER,
    PHOTO_GALLERY = "photoGallery",
    // VIDEO_GALLERY,
    // CONTACT_US,
    // ABOUT_US,
    // POST_SINGLE,
    POST_LIST = "postList",
    POST_BLOG = "postBlog",
    // SEARCH,
    // RANDOM_IMAGE,
    // LOGIN,
    // VERTICAL_MENU,
    HORIZONAL_MENU = "horizonalMenu",
    // LANGUAGE_SWITCHER,
    // PUBLICATION,
    // MESSAGE,
    // THYME,
    // COPYwRIGHT,

    //...
}

export enum MenuItemType {
    INTERNAL = 0,
    EXTERNAL,
}
export enum NewTapOptions {
    true = 0,
    false,
}
export enum ContentType {
    POST = "post",
    IMAGE = "image",
    VIDEO = "video",
    FILE = "file",
    SERVICE = "service",
    SLIDERS = "sliders",
    SECTION = "section",
    MAGAZINE = "magazine",
    ENCYCLOPEDIA = "encyclopedia",
}

export enum SubType {
    ARTICLES = "articles",
    MESSAGES = "messages",
    EVENTS = "events",
    NEWS = "news",
    INITIATIVES = "initiatives",
    INV_OPPS = "investmentOpportunities",
    OPEN_DATAS = "openDatas",
    OPINIONS = "opinions",
    ADS = "advertisments",
    PUBLICATIONS = "publications",
    GENERAL_PAGES = "generalPages",
    LIVE_BROADCASTS = "liveBroadcasts",
    SLIDERS = "sliders",
    FAQ = "faq",
    ROOMS = "rooms",
    NOTIFICATIONS = "notifications",
    INDICATORS = "indicators",
    PARTNERS = "partners",
    LAWS = "laws",
    POLICIES = "policies",
    BASIC_PAGE = "basicPage",
    WRITER = "writer",
    ENCYCLOPEDIA = "encyclopedia",
}
export enum TrusteeType {
    ALL = "all",
    OFFICES = "offices",
    MEMBERS = "members",
}
