post:
    summary: Update
    operationId: UpdateConfiguration
    description: <p>Update a new <b>Configuration</b>. <p>Available for <b>adimn</b></p>

    tags:
        - configuration
    parameters:
        - $ref: "../../parameters/header/token.yaml"
        - $ref: "../../parameters/path/id.yaml"
        - $ref: "../../parameters/header/language.yaml"
    requestBody:
        $ref: "../../requests/configuration/ConfigurationUpdateInput.yaml"
    responses:
        "201":
            $ref: "../../responses/configuration/Configurations.yaml"

        "401":
            $ref: "../../responses/common/InvalidParameter.yaml"
        "402":
            $ref: "../../responses/common/Unauthorized.yaml"
        "403":
            $ref: "../../responses/common/Forbidden.yaml"
        "404":
            $ref: "../../responses/configuration/ConfigurationExists.yaml"

        default:
            $ref: "../../responses/common/UnexpectedError.yaml"
