get:
    summary: configuration
    operationId: configurationById
    description: <p> get  <b>configuration</b>Available for <b>admin</b></p>

    tags:
        - configuration
    parameters:
        - $ref: "../../parameters/header/token.yaml"
        - $ref: "../../parameters/path/id.yaml"

    responses:
        "200":
            $ref: "../../responses/configuration/Configuration.yaml"
        "401":
            $ref: "../../responses/common/Unauthorized.yaml"
        "402":
            $ref: "../../responses/common/NotFound.yaml"
        "403":
            $ref: "../../responses/common/Forbidden.yaml"
        default:
            $ref: "../../responses/common/UnexpectedError.yaml"
