get:
  summary: List
  operationId: listOfConfigurations
  description: <p>List all  <b>Configuration</b></p>
  tags:
  - configuration
  parameters:
    - $ref: "../../parameters/header/token.yaml"
    - $ref: "../../parameters/header/language.yaml"
    - $ref: "../../parameters/query/limit.yaml"
    - $ref: "../../parameters/query/offset.yaml"
  
  responses:
    '200':
      $ref: "../../responses/configuration/Configurations.yaml"
    '401':
      $ref: "../../responses/common/Unauthorized.yaml"
    '402':
      $ref: "../../responses/common/Forbidden.yaml"
    default:
      $ref: "../../responses/common/UnexpectedError.yaml"

post:
  summary: Create
  operationId: createConfiguration
  description: <p>Creates a new <b>Configuration</b>. <p>Available for <b>adimn</b></p>

  tags:
  - configuration
  parameters:
    - $ref: "../../parameters/header/token.yaml"
    - $ref: "../../parameters/header/language.yaml"
  requestBody:
    $ref: "../../requests/configuration/ConfigurationInput.yaml"
  responses:
    '201':
      $ref: "../../responses/configuration/Configuration.yaml"
    
    '401':
      $ref: "../../responses/common/InvalidParameter.yaml" 
    '402':
      $ref: "../../responses/common/Unauthorized.yaml"     
    '403':
      $ref: "../../responses/common/Forbidden.yaml"    
    '404':
      $ref: "../../responses/configuration/ConfigurationExists.yaml"
    
    
    default:
      $ref : "../../responses/common/UnexpectedError.yaml"

