type: object
properties:
    title:
        type: string
        example: webiste language
    description:
        type: string
        example: defualt language used for website
    key:
        type: string
        example: language
    value:
        type: string
        example: arabic
