get:
  summary: careerApplications
  operationId: showCareerApplicationsById
  description: <p> show all applications belong to one  <b>career</b>Available for <b>Admin</b></p>

  tags:
  - career
  parameters:
    - $ref: "../../parameters/header/token.yaml"
    - $ref: "../../parameters/path/id.yaml"

  responses:
    '200':
      $ref: "../../responses/career/CareerApplications.yaml"
    '401':
      $ref: "../../responses/common/Unauthorized.yaml"
    '404':
      $ref: "../../responses/common/NotFound.yaml"
    '403':
      $ref: "../../responses/common/Forbidden.yaml"  
    '405':
      $ref: "../../responses/common/InvalidParameter.yaml"  
    default:
      $ref : "../../responses/common/UnexpectedError.yaml"
